# -*- coding: utf-8 -*-
"""wordRelay.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p5Uq-1pXWnXZ-cPirLfFEMA3SNr7tec8
"""

pip install jamo

import csv
from jamo import h2j, j2hcj, j2h
import random

# 글자를 분해해서 반환
def splitText(text):
    return j2hcj(h2j(text))

# 분해한 초성, 중성, 종성을 합쳐서 글자로 반환
def combine(datas):
    if len(datas) == 2 : 
        return j2h(datas[0], datas[1]) 
    elif len(datas) == 3: 
        return j2h(datas[0] ,datas[1] ,datas[2])

# 한국어 사전 불러오기
f = open('drive/MyDrive/ColabResources/WordRelay/kr_korean2.csv','r')
rdr = csv.reader(f)
wordList = []
for line in rdr:
    if len(line[0]) != 1:
        wordList.append(line[0])
f.close()

userWord = None
aiWord = None
usedWordList = []

# 마지막 글자를 두음법칙으로 변경한 단어리스트 반환
def duumRule(word):
    lastTexts = []
    lastTexts.append(word[len(word)-1])
    st = splitText(lastTexts[0])
    if st[0] == 'ㄴ':
        st = 'ㅇ'+st[1:]
        lastTexts.append(combine(st))
    elif st[0] == 'ㄹ':
        st = 'ㅇ'+st[1:]
        lastTexts.append(combine(st))
        st = 'ㄴ'+st[1:]
        lastTexts.append(combine(st))
    return lastTexts

# 두음법칙 함수 사용 ex)
duumRule("유령")

def checkUserWord(userWord):
    if aiWord != None:
        if userWord[0] in duumRule(aiWord) and userWord in wordList and userWord not in usedWordList:
            return True
        else: # 틀린 이유 알려주기
            if userWord[0] not in duumRule(aiWord):
                print("글자가 이어지지 않습니다.")
            if userWord not in wordList:
                print("사전에 없는 단어입니다.")
            if userWord in usedWordList:
                print("이미 사용한 단어입니다.")
            return False
    else:
        return True # aiWord가 None일 때 그냥 넘기기

# 이어지는 단어 찾아서 추가
# 전부 추가했으면 랜덤으로 골라서 반환
def aiWordRelay(userWord):
    lastTexts = duumRule(userWord)
    randWordList = []
    for word in wordList:
        if word[0] in lastTexts and word not in usedWordList: # 글자가 이어지고, 사용한 단어에 포함되지 않을 때
            randWordList.append(word)
    if len(randWordList) == 0:
        return None
    else:
        randWord = randWordList[random.randrange(0, len(randWordList))]
        return randWord

# 게임 시작
while True:
    userWord = input("단어를 입력하세요 : ")
    # 정답을 입력했을 때
    if checkUserWord(userWord):
        usedWordList.append(userWord) # 사용한 단어에 추가
        aiWord = aiWordRelay(userWord)
        if aiWord == None:
            print("당신이 이겼습니다.")
            break
        usedWordList.append(aiWord) # 사용한 단어에 추가
        print("AI : ", aiWord)
    # 오답을 입력했을 때
    else:
        print("틀렸습니다.")
        retry = input("다시하시겠습니까? (예 or 아니오) : ")
        if retry == '예': # 재시작
            userWord = None
            aiWord = None
            usedWordList.clear()
        elif retry == '아니오': # 끝내기
            break